{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "parallax.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "parallax.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "parallax.selectorLabels" . | nindent 4 }}
{{- end }}

