apiVersion: v2
name: parallax
description: A Helm chart for deploying the Parallax Operator
type: application
version: 0.1.2
appVersion: 0.1.2
maintainers:
  - name: Matan Ryngler
    email: matan@example.com
keywords:
  - operator
  - kubernetes
  - batch
  - parallel-processing
home: https://github.com/matanryngler/parallax
sources:
  - https://github.com/matanryngler/parallax 